# @format

version: "3"

services:
  nginx_lb:
    build: .
    ports:
      - 80:80

  node1:
    build: app
    environment:
      - APP_ID=1
      - PORT=2222
  node2:
    build: app
    environment:
      - APP_ID=2
      - PORT=3333
  node3:
    build: app
    environment:
      - APP_ID=3
      - PORT=4444
  node4:
    build: app
    environment:
      - APP_ID=4
      - PORT=5555
